// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC06GdE0jALpQSGBKMdxNeg4zgeOecN1h8',
    appId: '1:650823189030:web:3864a88775f412d53d9ce7',
    messagingSenderId: '650823189030',
    projectId: 'webmarket-6e86f',
    authDomain: 'webmarket-6e86f.firebaseapp.com',
    databaseURL: 'https://webmarket-6e86f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'webmarket-6e86f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmtHUm_zw8juAs6CnHsqyIV9BUeLApBU',
    appId: '1:650823189030:android:c614af7997b410093d9ce7',
    messagingSenderId: '650823189030',
    projectId: 'webmarket-6e86f',
    databaseURL: 'https://webmarket-6e86f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'webmarket-6e86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfS5NNVJcjQ3oTX00WqeseWGOVZNeS5y8',
    appId: '1:650823189030:ios:686a8ccf50cb01933d9ce7',
    messagingSenderId: '650823189030',
    projectId: 'webmarket-6e86f',
    databaseURL: 'https://webmarket-6e86f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'webmarket-6e86f.appspot.com',
    iosBundleId: 'com.example.webShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfS5NNVJcjQ3oTX00WqeseWGOVZNeS5y8',
    appId: '1:650823189030:ios:686a8ccf50cb01933d9ce7',
    messagingSenderId: '650823189030',
    projectId: 'webmarket-6e86f',
    databaseURL: 'https://webmarket-6e86f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'webmarket-6e86f.appspot.com',
    iosBundleId: 'com.example.webShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC06GdE0jALpQSGBKMdxNeg4zgeOecN1h8',
    appId: '1:650823189030:web:9e5018c21e522ebb3d9ce7',
    messagingSenderId: '650823189030',
    projectId: 'webmarket-6e86f',
    authDomain: 'webmarket-6e86f.firebaseapp.com',
    databaseURL: 'https://webmarket-6e86f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'webmarket-6e86f.appspot.com',
  );

}